#!/usr/bin/env python3

"""
Author: HealthTechKid
Date: 18 / 05 / 2024
Purpose: Use class operator to transform an integer to strings
and concatenate them
"""

my_string = "I want to buy " + str(10) + " bottles of water."
print(my_string)
